//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIC24FlashProgrammer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIC24FlashProgrammer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application file not found. {0}.
        /// </summary>
        internal static string AppFileNotFound {
            get {
                return ResourceManager.GetString("AppFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex files (*.hex)|*.hex|All Files (*.*)|*.*.
        /// </summary>
        internal static string ApplicationFileFilter {
            get {
                return ResourceManager.GetString("ApplicationFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID is 0x{0:X2}.
        /// </summary>
        internal static string ApplicationID {
            get {
                return ResourceManager.GetString("ApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , program executive is loaded.
        /// </summary>
        internal static string ApplicationIDLoaded {
            get {
                return ResourceManager.GetString("ApplicationIDLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , program executive needs to be loaded.
        /// </summary>
        internal static string ApplicationIDNotLoaded {
            get {
                return ResourceManager.GetString("ApplicationIDNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino was reset.
        /// </summary>
        internal static string ArduinoReset {
            get {
                return ResourceManager.GetString("ArduinoReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block erased.
        /// </summary>
        internal static string BlockErased {
            get {
                return ResourceManager.GetString("BlockErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip erased.
        /// </summary>
        internal static string ChipErased {
            get {
                return ResourceManager.GetString("ChipErased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseSerial {
            get {
                return ResourceManager.GetString("CloseSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable debug.
        /// </summary>
        internal static string DebugDisable {
            get {
                return ResourceManager.GetString("DebugDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable debug.
        /// </summary>
        internal static string DebugEnable {
            get {
                return ResourceManager.GetString("DebugEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode disabled.
        /// </summary>
        internal static string DebugOff {
            get {
                return ResourceManager.GetString("DebugOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode enabled.
        /// </summary>
        internal static string DebugOn {
            get {
                return ResourceManager.GetString("DebugOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID: 0x{0:X4}.
        /// </summary>
        internal static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model: {0}.
        /// </summary>
        internal static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ICSP mode to update.
        /// </summary>
        internal static string DevinfoNone {
            get {
                return ResourceManager.GetString("DevinfoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered EICSP mode.
        /// </summary>
        internal static string EnteredEICSP {
            get {
                return ResourceManager.GetString("EnteredEICSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered ICSP mode.
        /// </summary>
        internal static string EnteredICSP {
            get {
                return ResourceManager.GetString("EnteredICSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIPE files (RIPE*.hex)|RIPE*.hex|All Files (*.*)|*.*.
        /// </summary>
        internal static string ExecutiveFileFilter {
            get {
                return ResourceManager.GetString("ExecutiveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program executive {0}.
        /// </summary>
        internal static string ExecutiveVersion {
            get {
                return ResourceManager.GetString("ExecutiveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exited ICSP mode.
        /// </summary>
        internal static string ExitICSP {
            get {
                return ResourceManager.GetString("ExitICSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCU reset, application running.
        /// </summary>
        internal static string MCUReset {
            get {
                return ResourceManager.GetString("MCUReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected memory region is blank.
        /// </summary>
        internal static string MemoryBlank {
            get {
                return ResourceManager.GetString("MemoryBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected memory region is NOT blank.
        /// </summary>
        internal static string MemoryNotBlank {
            get {
                return ResourceManager.GetString("MemoryNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more pages.
        /// </summary>
        internal static string NoPages {
            get {
                return ResourceManager.GetString("NoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenSerial {
            get {
                return ResourceManager.GetString("OpenSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application.
        /// </summary>
        internal static string ProgressLoadingApp {
            get {
                return ResourceManager.GetString("ProgressLoadingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading program executive.
        /// </summary>
        internal static string ProgressLoadingExec {
            get {
                return ResourceManager.GetString("ProgressLoadingExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying application.
        /// </summary>
        internal static string ProgressVerifyingApp {
            get {
                return ResourceManager.GetString("ProgressVerifyingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying program executive.
        /// </summary>
        internal static string ProgressVerifyingExec {
            get {
                return ResourceManager.GetString("ProgressVerifyingExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received invalid data: {0}.
        /// </summary>
        internal static string ReceivedInvalid {
            get {
                return ResourceManager.GetString("ReceivedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application code file.
        /// </summary>
        internal static string SelectApplicationFile {
            get {
                return ResourceManager.GetString("SelectApplicationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select program executive file.
        /// </summary>
        internal static string SelectExecutiveFile {
            get {
                return ResourceManager.GetString("SelectExecutiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial port must be closed. {0}.
        /// </summary>
        internal static string SerialPortError {
            get {
                return ResourceManager.GetString("SerialPortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application....
        /// </summary>
        internal static string StatusLoadingApp {
            get {
                return ResourceManager.GetString("StatusLoadingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading program executive....
        /// </summary>
        internal static string StatusLoadingExec {
            get {
                return ResourceManager.GetString("StatusLoadingExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying application....
        /// </summary>
        internal static string StatusVerifyingApp {
            get {
                return ResourceManager.GetString("StatusVerifyingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program executive loaded, verifying....
        /// </summary>
        internal static string StatusVerifyingExec {
            get {
                return ResourceManager.GetString("StatusVerifyingExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed at page address {0}.
        /// </summary>
        internal static string VerificationFailed {
            get {
                return ResourceManager.GetString("VerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application verified.
        /// </summary>
        internal static string VerifiedApp {
            get {
                return ResourceManager.GetString("VerifiedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program executive verified.
        /// </summary>
        internal static string VerifiedExec {
            get {
                return ResourceManager.GetString("VerifiedExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not supported in current ICSP mode.
        /// </summary>
        internal static string WrongMode {
            get {
                return ResourceManager.GetString("WrongMode", resourceCulture);
            }
        }
    }
}
